<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>VitalCare.Abp</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VitalCare.Abp.HttpApi.Host</AssemblyName>
    <UserSecretsId>15c0173c-8fc7-45ab-8bb6-323c748bb9a5</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Volo.Abp.AspNetCore" Version="8.2.0" />
    <PackageReference Include="Volo.Abp.Autofac" Version="8.2.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="8.2.0" />
    <PackageReference Include="Volo.Abp.Swashbuckle" Version="8.2.0" />
    <PackageReference Include="Volo.Abp.Castle.Core" Version="8.2.0" />
    <PackageReference Include="Volo.Abp.Uow" Version="8.2.0" />
    <ProjectReference Include="..\VitalCare.Abp.HttpApi\VitalCare.Abp.HttpApi.csproj" />
    <ProjectReference Include="..\VitalCare.Abp.EntityFrameworkCore\VitalCare.Abp.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\VitalCare.Abp.Application\VitalCare.Abp.Application.csproj" />
  </ItemGroup>
</Project>
